# Generated by Django 5.2.5 on 2025-12-03 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discount", "0088_merge_20251013_1142"),
        ("product", "0202_category_product_category_tree_id_lf1e1"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariantchannellisting",
            name="applied_rule",
            field=models.ForeignKey(
                blank=True,
                help_text="The promotion rule that was applied to get the discounted price.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applied_variant_listings",
                to="discount.promotionrule",
            ),
        ),
    ]
