# Generated by Django 5.2.8 on 2026-02-22 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0203_productvariantchannellisting_applied_rule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariantchannellisting",
            name="applied_rule",
        ),
    ]
