# Generated by Django 5.2.8 on 2026-04-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0203_productvariantchannellisting_applied_rule"),
        ("tax", "0011_merge_20250530_0929"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["rating", "name", "slug", "id"],
                name="product_pro_rating_f2d4e8_idx",
            ),
        ),
    ]
