# Generated by Django 5.2.8 on 2026-04-07 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0035_alter_appextension_mount"),
        ("app", "0035_appproblem"),
    ]

    operations = []
