# Generated by Django 5.2.8 on 2026-02-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0088_reapply_fix_shared_address_instances"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutline",
            name="price_discounted_override",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=20, null=True
            ),
        ),
    ]
