# Generated by Django 5.2.1 on 2025-07-08 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discount", "0086_promotionrule_customer_groups"),
        ("discount", "0087_merge_20250630_1332"),
    ]

    operations = []
