# Generated by Django 5.2.5 on 2025-10-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discount", "0086_promotionrule_customer_groups"),
        ("discount", "0087_merge_20250630_1332"),
    ]

    operations = []
