# Generated by Django 5.2.8 on 2026-02-22 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discount", "0088_merge_20251013_1142"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promotionrule",
            name="customer_groups",
        ),
    ]
