# Generated by Django 5.2.8 on 2026-03-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discount", "0089_remove_promotionrule_customer_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucher",
            name="exclude_discounted_products",
            field=models.BooleanField(default=False),
        ),
    ]
