# Generated by Django 5.2.5 on 2025-10-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0087_customergroup"),
        ("account", "0095_repopulate_user_number_of_orders"),
    ]

    operations = []
