# Generated by Django 5.2.8 on 2026-03-17 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("giftcard", "0022_merge_20250527_1210"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giftcard",
            name="code",
            field=models.CharField(
                db_index=True,
                max_length=32,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(8)],
            ),
        ),
    ]
